title = "Bits By Me"
baseURL = "https://bitsby.me"
languageCode = "en-us"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 20
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  #facebook = ""
  twitter = "https://twitter.com/dvhthomas"
  instagram = ""
  youtube = ""
  github = "https://github.com/dvhthomas"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/dylan-thomas/"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 3
