baseURL = "https://bitsby.me/"
languageCode = "en-us"
title = "Bits By Me"

paginate = 10
ignoreErrors = ["error-remote-getjson"]

[params]
    homeText = "tech cloud geo learning"
    dateFormat = "January 2, 2006"
    description = "The personal website, blog and dev diary of Dylan Thomas"


[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[menu]
    [[menu.main]]
        name = "Home"
        pre = "home"
        url = "/"
        weight = 1
    [[menu.main]]
        name = "Blog"
        pre = "edit"
        url = "/blog/"
        weight = 2
    [[menu.main]]
        name = "TIL"
        pre = "award"
        url = "/til/"
        weight = 3
    [[menu.main]]
        name = "Tags"
        pre = "tag"
        url = "/tags/"
        weight = 4
    [[menu.main]]
        name = "Series"
        pre = "book"
        url = "/series/"
        weight = 5
    [[menu.main]]
        name = "About"
        pre = "user"
        url = "/about/"
        weight = 6

[taxonomies]
  tag = "tags"
  series = "series"

[permalinks]
  blog = "/:year/:month/:title"
  til = "til/:year-:month-:day/"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "github"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
