baseURL = "https://bitsby.me/"
languageCode = "en-us"
title = "Bits By Me"

paginate = 3
enableRobotsTXT = true

[params]
    homeText = "Tech cloud geo learning"
    dateFormat = "January 2, 2006"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"


[menu]
    [[menu.main]]
        name = "Home"
        pre = "home"
        url = "/"
        weight = 1
    [[menu.main]]
        name = "Blog"
        pre = "edit"
        url = "/blog/"
        weight = 2
    [[menu.main]]
        name = "TIL"
        pre = "award"
        url = "/til/"
        weight = 3
    [[menu.main]]
        name = "Tags"
        pre = "tag"
        url = "/tags/"
        weight = 4
    [[menu.main]]
        name = "About"
        pre = "user"
        url = "/about/"
        weight = 5

[taxonomies]
  tag = "tags"

[permalinks]
  blog = "/:year/:month/:title"
  til = "/:year/:month/:day/:title"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "github"